version: '3.8'

networks:
  user-management-system:
    name: user-management-system

volumes:
  user-management-system:
    name: user-management-system

services:
  user-management-system:
    image: user-management-system
    container_name: user-management-system
    build: .
    env_file:
      - .env
    volumes:
      - user-management-system:/root
      - ./backend:/root/backend
      - ./CLI-Tests:/root/CLI-Tests
    ports:
      - "8080:8080"
    networks:
      - user-management-system
