version: '3.8'

networks:
  nlab:
    name: nlab

volumes:
  vlab:
    name: vlab
  # postgres_data:
  #   name: postgres_data
  # pgadmin_data:
  #   name: pgadmin_data

services:
  lab:
    image: ilab
    container_name: clab
    build: .
    env_file:
      - .env
    volumes:
      - vlab:/var/www/html
      - ./lab:/root/lab
      - ./zshrc:/root/.zshrc
      - ./zsh_history:/root/.zsh_history
    networks:
      - nlab
    # depends_on:
    #   - db
    
  # db:
  #   image: postgres:13
  #   container_name: postgres_db
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   environment:
  #     - POSTGRES_DB=${DB_NAME}
  #     - POSTGRES_USER=${DB_USER}
  #     - POSTGRES_PASSWORD=${DB_PASSWORD}
  #   networks:
  #     - nlab

  # pgadmin:
  #   image: dpage/pgadmin4
  #   container_name: pgadmin
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
  #     PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
  #   volumes:
  #     - pgadmin_data:/var/lib/pgadmin
  #   ports:
  #     - "5050:80"
  #   networks:
  #     - nlab
  #   depends_on:
  #     - db