groups:
  - name: all-instances-alerts
    rules:
      # Alert if any monitored exporter is down
      - alert: InstanceDown
        expr: up == 0
        for: 10s
        labels:
          severity: critical
        annotations:
          summary: "Instance Down"
          description: "{{ $labels.job }} instance {{ $labels.instance }} is down for more than 10 seconds."
