global:
  scrape_interval: 10s
  evaluation_interval: 10s

alerting:
  alertmanagers:
    - scheme: https
      static_configs:
        - targets:
            - localhost:9093
      tls_config:
        insecure_skip_verify: true

rule_files:
  - '/etc/prometheus/alert_rules.yml'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']
    scheme: https
    tls_config:
      insecure_skip_verify: true

  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx_exporter:9113']
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']

