{
 "title": "NGINX Dashboard",
 "tags": [
  "nginx",
  "prometheus",
  "nginx prometheus exporter"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "instance",
    "query": "label_values(nginx_up, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "NGINX Status for $instance",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "repeat": "instance",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "nginx_exporter_build_info" }
   ]
  },
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "rate(promhttp_metric_handler_requests_total{code=\"200\", instance=\"nginx_exporter:9113\", job=\"nginx\"}[$__rate_interval])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(promhttp_metric_handler_requests_total{code=\"500\", instance=\"nginx_exporter:9113\", job=\"nginx\"} [$__rate_interval])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(promhttp_metric_handler_requests_total{code=\"400\", instance=\"nginx_exporter:9113\", job=\"nginx\"} [$__rate_interval])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(promhttp_metric_handler_requests_total{code=\"201\", instance=\"nginx_exporter:9113\", job=\"nginx\"} [$__rate_interval])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(promhttp_metric_handler_requests_total{code=\"404\", instance=\"nginx_exporter:9113\", job=\"nginx\"} [$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active Connections",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "promhttp_metric_handler_requests_in_flight{instance=~\"$instance\"}",
     "legendFormat": "{{instance}} active"
    },
    {
     "expr": "nginx_connections_reading{instance=~\"$instance\"}",
     "legendFormat": "{{instance}} reading"
    },
    {
     "expr": "nginx_connections_waiting{instance=~\"$instance\"}",
     "legendFormat": "{{instance}} waiting"
    },
    {
     "expr": "nginx_connections_writing{instance=~\"$instance\"}",
     "legendFormat": "{{instance}} writing"
    }
   ]
  },
  {
   "title": "Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Total requests",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(promhttp_metric_handler_requests_total{instance=~\"$instance\"}[30m])",
     "legendFormat": "{{instance}} total requests"
    }
   ]
  }
 ]
}